### ISSUE TITLE
Robot doesn't move in simulation in ROS kinetic.

### ISSUE THREAD

**Issue by nikv96** [RobotnikAutomation/rbcar_sim#10]
Seems like the URDF is incorrectly configured. 
Getting the following error 'Could not load controller 'left_front_shock_controller' because controller type 'effort_controllers/JointEffortController' does not exist.'

![image](https://user-images.githubusercontent.com/10889883/39917884-7878e968-5541-11e8-9e5b-823efba32f12.png)

**Comment by RomanRobotnik** [comment]
Hi,

Do you have installed the effort-controllers package?

$sudo apt-get install ros-kinetic-effort-controllers 

Regards

**Comment by amattag** [comment]
Hi,

I have a similar problem. After downloading, compiling and running all the packages I finally got the rbcar up and running with all its sensors and controllers, but it does not move. Even the global and local planners seem to work fine (see attached figures), but I do not get any motion from the car.

![rbcar-01](https://user-images.githubusercontent.com/4758119/49283728-74615480-f48a-11e8-880a-bb489e51cb1d.png)
![rbcar-02](https://user-images.githubusercontent.com/4758119/49283729-74f9eb00-f48a-11e8-9dd1-a113da151d26.png)

Any help will be welcomed,

Kind regards,

Antonio.

**Comment by David-rn** [comment]
Hi, 

The RBCAR uses `ackermann_msgs/AckermannDriveStamped` message and move_base provides `geometry_msgs/Twist`. This is why you don't get any motion from the car. [Here](http://wiki.ros.org/teb_local_planner/Tutorials/Planning%20for%20car-like%20robots) you have an explanation of planning for car-like robots with navigation stack.

Regards.

**Comment by amattag** [comment]
Thanks!

I forgot to mention that this package:
https://github.com/wilselby/diy_driverless_car_ROS/tree/master/rbcar_twist2ack

does the conversion.
